### ISSUE TITLE
[docker] No sensors found in configuration file "config.ini"

### ISSUE THREAD

**Issue by Giel538** [ThomDietrich/miflora-mqtt-daemon#100]
Hi.

I'm trying to run the mqtt-daemon in docker.

Everything installed fine but when i run the docker i keep getting this error:

[2020-02-14 15:08:27] No sensors found in configuration file "config.ini"

In my docker compose file i have this line:

      - /data/miflora2mqtt/config.ini:/opt/miflora-mqtt-daemon/config.ini

So the config is stored in opt/miflora-mqtt-daemon/config.ini. When i copy this file back from the docker to my local hard drive i see the right config.ini In this file i have this:

```
[Sensors]

# Add your Mi Flora sensors here. Each sensor consists of a name and a Ethernet MAC address.
# Additional location information can be added to the name, delimited by an '@'.
# Scan for sensors from the command line with:
#    $ sudo hcitool lescan
#
# Examples:
#
Flower_1 = C4:7C:8D:6A:74:7F
Flower_2 = C4:7C:8D:6A:74:23
Flower_3 = C4:7C:8D:6B:1A:70

```

Do you have any idea what i can try?

**Comment by CWempe** [comment]
According to the Instruction (https://github.com/ThomDietrich/miflora-mqtt-daemon#usage-with-docker) your path is wrong.

The `config.ini` inside the container is located in `/config`.

So you line should look like this, I guess.

```
  - /data/miflora2mqtt/config.ini:/config/config.ini
´´´

**Comment by ThomDietrich** [comment]
Thanks @CWempe.
@Giel538 hope it works now. Would you like to provide your docker-compose.yml and please feel free to suggest a change to the README to remove this issue for others.

**Comment by Giel538** [comment]
This is my docker file now:

```
version: '3.6'
services:  
  portainer:
    image: ruimarinho/miflora-mqtt
    container_name: "miflora-mqtt"
    restart: "always"
    network_mode: host    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/miflora2mqtt/config.ini:/config/config.ini
    environment:
      - TZ=Europe/Amsterdam

```

Still the same problem :(


```
Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon
Source: https://github.com/ThomDietrich/miflora-mqtt-daemon


[2020-02-18 20:12:34] No sensors found in configuration file "config.ini
```
