### ISSUE TITLE
Home Assistant example

### ISSUE THREAD

**Issue by itayraviv** [ThomDietrich/miflora-mqtt-daemon#99]
I followed the instructions and installed this great project on a RPi3 trying to send MiFlora sensors data back the my main HA system running on an Ubuntu server.
I see in my MQTT broker a successful connection from the RPi.
now, how can I present the sensors data as sensors in HA? 
can someone share the needed "plant" and "sensor" config?
Thanks !

**Comment by bangom** [comment]
Try latest git version, it has improved HA sensor discovery (see @ #101 ). After successful miflora-mqtt-daemon configuration (for home-assistant) and connecting it to integrated HA MQTT broker, you should see each Miflora sensor as separate HA Device (with lux, temp, moisture, conductivity and battery sensors/entities) under HA MQTT broker Integrations.

Regarding Plant component (https://www.home-assistant.io/integrations/plant/): this must be defined manually in configuration.yaml. For example if you have mqtt-daemon advertising Plant01 Miflora sensor, then configuration.yams could look like this:
```
plant:
  plant01:
    sensors:
      moisture: sensor.plant01_moisture
      battery: sensor.plant01_battery
      temperature: sensor.plant01_temperature
      conductivity: sensor.plant01_conductivity
      brightness: sensor.plant01_light
    min_moisture: 28
    max_moisture: 75
    min_battery: 20
    min_conductivity: 100
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 35
    min_brightness: 2500
    max_brightness: 55000
    check_days: 3
```

**Comment by ThomDietrich** [comment]
Thanks @bangom for your addition!
Just to clarify, it doesn't have to the be integrated MQTT broker. Any connected broker will do.

Thanks for the example. Would you want to create a pull request against the README?

**Comment by bangom** [comment]
> Thanks @bangom for your addition!
> Just to clarify, it doesn't have to the be integrated MQTT broker. Any connected broker will do.
> 
I suspect if one uses general (external) MQTT broker with HA, then one must modify HA configuration.yaml:

```
# Example configuration.yaml entry
mqtt:
  discovery: true
  discovery_prefix: homeassistant
```
With integrated MQTT broker this is enabled by default or offered during MQTT Integration setup...

> Thanks for the example. Would you want to create a pull request against the README?

Regarding plant component configuration.yaml example? Personally I'm not satisfied with this manual solution. My goal is that miflora-mqtt-daemon will add Plant component device (for monitoring Plant state based on particular plant type) automatically (via HA API) ... possibly customised Plant component, because current implementation is quite limited and not user friendly. Final goal is to to have miflora in HA more like "ESPhome experience" compared to "Tasmota in HA via MQTT"... (try for yourself :)
